<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleblog"
 *
 * Auto generated by Extension Builder 2016-07-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'GB Redirect',
	'description' => 'Redirects to pages',
	'category' => 'plugin',
	'author' => 'Alexander Averbuch',
	'author_email' => 'alav@gmx.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
                        'femanager' => '1.0.0-100.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);