<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gborderapi"
 *
 * Auto generated by Extension Builder 2016-11-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Gigabonus Tools',
	'description' => '',
	'category' => 'services',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'femanager' => '2.6.0-3.0.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
